
POST  http://localhost:5001/user/register
content-type: application/json

{
  "username" : "gina",
  "email" : "gina@gmail.com",
  "password" : "password"
}

###

GET http://localhost:5001/user

###

POST http://localhost:5001/photo
content-type: application/json

{
    "url": "https://unsplash.com/photos/6J--NXulQCs",
    "UserId" : 1
}

###
GET http://localhost:5001/photo

###
GET http://localhost:5001/user/gina

